### ISSUE TITLE
Sections required

### ISSUE THREAD

**Issue by Antes** [Archer70/SkitchBB#2]
Since I can't catch you on IRC lately 😆 

I need you to enable the following sections;

* sidebar
* top_section
* bot_section
* footer

I'm already coding sidebars for specific purposes I just don't have motivation to go into the source yet to find out how to enable them tbh.

Thanks ^^

**Comment by Archer70** [comment]
I'm gonna go ahead and close this for the time being. We can revisit it if/when the theme is being developed again. :)
